### ISSUE TITLE
[BE] 게시글 필터링하여 목록 반환

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#102]
## Description
여러 필터링 기준을 바탕으로 게시글 필터링하여 목록 반환

## To-do
- [x] 마감 여부
- [x] 지역 (최대 3개 선택 가능)
- [x] 수리 서비스(다중 선택)
- [x] 정비 서비스 (다중 선택)
- [x] QueryDSL 공부
