### ISSUE TITLE
[FE] 사용자 별 견적 문의 게시물 조회

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#112]
## To-do
- [x] 사용자 + 게시물 작성자인 경우 화면 구현
- [x] 사용자 + 게시물 작성자가 아닌 경우 화면 구현
- [x] 센터 + 경매에 참여중인 경우
- [x] 센터 + 경매에 참여중이지 않은 경우
- [x] 로그인하지 않은 사용자인 경우 마감된 게시물만 접근 가능
