### ISSUE TITLE
[FE] webSocket 간헐적 끊김 예외 처리 구현

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#130]
## To-do
- [x] 연결이 끊어졌을 때 재연결 시도
- [x] 브라우저 종료, f5,, 등의 연결 끊길 시 처리
- [x] 기타 webSocket 끊김 공부 및 검색, 처리
