### ISSUE TITLE
[FE] WebSocket 종료 메세지 수정

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#134]
## To-do
- [x] 백엔드와 형식 맞추기
- [x] 경매 종료 시 댓글 작성자들에게 종료 모달 띄워줌
- [x] 경매 종료 시 게시글 작성자에게 종료 모달 띄워줌
