### ISSUE TITLE
[BE] 견적 게시물 작성 기능

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3rd/Team3-33ma3#14]
## Description
견적 게시물을 작성하는 기능

## To-do
- [x] 색상, 차종, 모델명 저장하기
- [x] 수리 종류, 정비 종류 저장하기
- [x] 반경안에 있는 수리 센터와 게시물 저장
- [x] 입력받은 주소 정보로 해당하는 구 찾아서 저장
- [x] 이미지랑 매핑하기
- [x] 테스트 코드 작성하기
