### ISSUE TITLE
[BE] 게시글 목록 조회 시 자신이 쓴 게시글만 볼 수 있도록 필터링 조건 추가

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#157]
## To-do
- [x] 댓글 목록 정렬 방식에서 센터 별점 순 나열 추가
- [x] 게시글 목록 필터링 조건으로 자신이 쓴 게시글만 보이기 추가
- [x] PostThumbnailDto에서 remainTime 필드 삭제
- [x] 게시글 내 댓글들의 평균 제시 가격 계산 방법 변경
