### ISSUE TITLE
[BE] 경매 웹소켓 통신 관련 수정

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#186]
## To-do
- [x] 해당 화면을 보고 있는 그 외 유저들에게도 경매 마감 메세지 전송
- [x] 회원가입 과정에서 프로필 추가하여 한번의 api로 요청할 수 있도록 수정
- [x] 댓글 업데이트 시 !해당하는 게시글!에 진입해있는 유저에게만 실시간 통신 쏴주기
