### ISSUE TITLE
[FE] 센터 채팅 리다이랙션 관련 기능 구현

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#188]
## Description
센터로 로그인 시 채팅방 리다이랙션 및 문의 내역, 채팅방 목록 관련 코드 구현

## To-do
- [x] 센터 문의 내역 리다이랙션 (Nav)
- [x] 센터 문의 내역 확인
- [x] 센터 채팅방 확인
- [x] 채팅방 이름 관련 확인
