### ISSUE TITLE
[FE] 양방향 통신 id 값 관련 버그 수정

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#193]
## To-do
- [x] NavItem으로 문의 내역 리다이랙션 추가
- [x] senderId, receieverId 수정
- [x] 채팅방에 있을 때 수신한 메시지의 noReadCount 값 0으로 수정
