### ISSUE TITLE
[BE] 견적 댓글 생성 기능

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#2]
## Description

댓글 생성

## To-do

- [x] 댓글 생성 요청 처리
- [x] 생성 성공 시 해당 시점까지의 평균 제시 가격 반환
- [x] 경매 완료시 댓글 작성 불가 기능 추가
- [x] 댓글 생성 성공시 보내지는 응답 내용 수정
