### ISSUE TITLE
[FE] 오류 수정

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#201]
## To-do
- [x] 필터링에서 기타 없애기
- [x] D-day 0부터 시작 가능하게 구현
- [x] 견적 제시 모달에서 가격 1부터 가능하게 구현 (봐야될듯)
- [x] 센터 리뷰 오류 수정
