### ISSUE TITLE
[FE] 채팅 기능 디테일 오류 수정

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#202]
## Description
채팅 읽음 처리가 반대로 되는 오류, 문의 버튼으로 리다이랙션시 centerId가 undefined인 오류, ChatList의 불필요한 useEffect 선언

## To-do
- [x] 채팅 읽음 처리 오류 수정
- [x] 문의 버튼의 리다이랙션 쿼리스트링 수정
- [x] ChatList 파일의 불필요한 useEffect 훅 제거
