### ISSUE TITLE
[BE] 게시글 관련 기능 테스트 코드 작성

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3rd/Team3-33ma3#205]
## Description
게시글 기능 관련 테스트 코드를 작성한다.

## To-do
- [x] postController 테스트 코드 작성
- 작성, 수정, 삭제
- [x] postService 테스트 코드 작성
- 작성, 수정, 삭제
- [x] postRepository 테스트 코드 작성
