### ISSUE TITLE
[MAIN] readme에 33MA3 서비스 설명 작성

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#21]
## Description

프로젝트를 진행할 서비스에 대한 간략한 설명 추가

## To-do
- [x] 서비스 간단 요약
- [x] 서비스 제시 배경
- [x] 핵심 기능
- [x] 백엔드 / 프론트엔드별 기술적 목표
- [x] 팀원 소개에서 각자 깃허브 링크 달기
