### ISSUE TITLE
[FE] 센터 회원가입시 위치 모달 사용

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#210]
## Description
센터의 회원가입을 진행할 때 위치를 직접 입력하는 방식이 아닌, 모달을 사용한다.

## To-do
- [x] 모달 회원가입 페이지에 연결
- [x] 설정한 주소와 위도, 경도 값 추출
- [x] 입력한 주소를 표시
