### ISSUE TITLE
[FE] 채팅 관련 오류 수정

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#223]
## Description
채팅 기능의 오류를 수정한다.

## To-do
- [ ] 문의 내역 목록 안읽은 메시지 기능 수정
- [ ] 채팅방 입장시 안읽은 메시지 초기화
- [ ] 채팅 읽음 처리 기능 수정
