### ISSUE TITLE
[BE] 위치, 문의 서비스 관련 테스트 코드 작성

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3rd/Team3-33ma3#230]
## Description
위치 기능, 문의 기능 관련 테스트 코드를 작성한다.

## To-do
- [x] 모든 위치 정보 내려주는 기능 관련 테스트
- [x] 반경 안 위치 정보 내려주는 기능 관련 테스트
- [x] 채팅방 만들기
- [x] 기존 채팅방 내역 내려주기
- [x] 기존 채팅 내용 내려주기
