### ISSUE TITLE
[BE] 회원가입, 로그인 관련 + jwt 기능 관련 테스트 코드 작성

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3rd/Team3-33ma3#233]
## Description
회원가입, 로그인 기능 테스트 코드 작성
## To-do
- [ ] 일반 사용자 회원가입
- [ ] 센터 사용자 회원가입
- [ ] 이미지 유무에 따른 회원가입
- [ ] 예외 테스트도 작성
- [ ] jwtService, jwtProvider 테스트 코드 작성
