### ISSUE TITLE
[BE] 프로젝트 구조 및 도메인 생성

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#4]
## Description

첫 프로젝트를 생성하고 협업에 필요한 도메인을 구현한다.

## To-do
- [x] 요구사항에 맞게 프로젝트 생성
- [x] be-dev 브랜치 형성
- [x] 도메인 클래스 구현
