### ISSUE TITLE
[FE] Modal 세부 기능 구현

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#54]
## To-do
- [x] InputText 컴포넌트 적용
- [x] 사용자 반경 입력에 따른 UI 표현
- [x] Title, Modal close 기능 구현
