### ISSUE TITLE
[FE] 게시물 작성 컴포넌트 구현

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#55]
## To-do
- [x] input range 구현
- [x] 드롭다운 버튼 구현
- [ ] react hook form 공부 및 사용
