### ISSUE TITLE
[BE] 견적 제시 댓글 삭제 기능

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#65]
## Description

 견적 제시 댓글 삭제 기능 구현

## To-do
- [x] 현재 경매 진행 중인 게시글만 댓글 삭제 가능하도록 구현
- [x] 댓글 작성자만 삭제 가능하도록 구현
- [x] 업데이트된 댓글 목록을 게시글 작성자에게 실시간 응답
- [x] 업데이트된 평균 제시 가격을 해당 게시글에 견적을 작성한 모든 서비스 센터들에게 실시간 응답
