### ISSUE TITLE
[BE] 테스트 코드 작성

### ISSUE THREAD

**Issue by Yang-soeun** [softeerbootcamp-3rd/Team3-33ma3#67]
## To-do
- [x] 로그인 관련 기능 테스트 코드 작성
- [x] 회원가입 관련 기능 테스트 코드 작성
- 일반 회원가입
- 센터 회원가입
- [x] 모든 센터 내려주는 기능 테스트 코드 작성
- [x] jwt 기능 테스트 코드 작성
