### ISSUE TITLE
[BE] 댓글 낙찰 처리 구현

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#74]
## Description

게시글 작성자가 원하는 댓글을 낙찰하는 기능 구현

## To-do
- [x] 게시글 마감 처리
- [x] 낙찰된 서비스 센터에게 메세지로 낙찰되었음을 보내주기
- [x] 낙찰된 댓글 낙찰 처리
- [x] 해당 게시글에 대해 연결되어있던 모든 웹 소켓 연결 close
