### ISSUE TITLE
[BE] 견적 문의 게시글 목록 조회 구현

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#80]
## Description
필터링을 걸지 않은 상태의 게시글 목록 조회 기능 구현

## To-do
- [x] 일반 유저: 모든 게시글에 대해 썸네일 반환
- [x] 서비스 센터: 글 작성자가 지정한 지역에 해당할 때만 게시글 목록에 포함, 마감된 게시글은 보여주지 않음
- [x] 프론트에서 가져다 쓰기 쉽도록 시간에 관한 요소 formatting하기
- [x] 게시글 별 댓글 카운트
- [x] 게시글 리스트 생성 시간 기준 최신순 정렬
