### ISSUE TITLE
[BE] 웹소켓 연결 방식 수정

### ISSUE THREAD

**Issue by jbonnie** [softeerbootcamp-3rd/Team3-33ma3#87]
## Description
게시글 세부사항 화면 진입시 웹소켓 연결, 화면 나갈시 연결 끊기
프론트에 보내주는 데이터 형식 수정 (json 형식에서 key-value를 가지도록)

## To-do
- [x] 웹소켓 세션 저장소 수정
- [x] 웹소켓 연결 엔드 포인트 수정
- [x] 웹소켓 연결 끊어질 시 저장소 청소 추가
