### ISSUE TITLE
[FE] Chip 컴포넌트 구현

### ISSUE THREAD

**Issue by chjih** [softeerbootcamp-3rd/Team3-33ma3#9]
## To-do
- [x] 버전 별로 스타일링
- [x] 재사용할 수 있도록 props로 버전 받아오기
- [x] 함수 포인터 props로 받아오기

## ETC
[https://velog.io/@syon013/Chip-Component-활용하기](https://velog.io/@syon013/Chip-Component-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0)
참고하여 구현
