### ISSUE TITLE
[FE] 게시물 작성 페이지에 Modal 적용 및 오류 수정

### ISSUE THREAD

**Issue by cmw9957** [softeerbootcamp-3rd/Team3-33ma3#92]
## Description
사용자의 위치에 대한 정보와 수리 센터 정보를 저장한다. 지도에 수리 센터에 대한 위치를 표시할 때 반경 범위 수정

## To-do
- [x] 게시물 작성 페이지에 Modal 적용
- [x] 상위 컴포넌트에 주소와 수리 센터 리스트 전달
- [x] 수리 센터 표시 관련 오류 수정
